In [4]:
import json
import requests
import prettytable
import tweepy
import numpy as np
import os
import pickle

In [5]:
headers = {'Content-type': 'application/json'}
data = json.dumps({"seriesid": ['CUUR0000SA0','SUUR0000SA0'],"startyear":"2011", "endyear":"2014"})
p = requests.post('https://api.bls.gov/publicAPI/v2/timeseries/data/', data=data, headers=headers)
data = json.loads(p.text)
data

{'Results': {'series': [{'data': [{'footnotes': [{}],
      'period': 'M12',
      'periodName': 'December',
      'value': '234.812',
      'year': '2014'},
     {'footnotes': [{}],
      'period': 'M11',
      'periodName': 'November',
      'value': '236.151',
      'year': '2014'},
     {'footnotes': [{}],
      'period': 'M10',
      'periodName': 'October',
      'value': '237.433',
      'year': '2014'},
     {'footnotes': [{}],
      'period': 'M09',
      'periodName': 'September',
      'value': '238.031',
      'year': '2014'},
     {'footnotes': [{}],
      'period': 'M08',
      'periodName': 'August',
      'value': '237.852',
      'year': '2014'},
     {'footnotes': [{}],
      'period': 'M07',
      'periodName': 'July',
      'value': '238.250',
      'year': '2014'},
     {'footnotes': [{}],
      'period': 'M06',
      'periodName': 'June',
      'value': '238.343',
      'year': '2014'},
     {'footnotes': [{}],
      'period': 'M05',
      'periodName': 'May',
      'value': '237.900',
      'year': '2014'},
     {'footnotes': [{}],
      'period': 'M04',
      'periodName': 'April',
      'value': '237.072',
      'year': '2014'},
     {'footnotes': [{}],
      'period': 'M03',
      'periodName': 'March',
      'value': '236.293',
      'year': '2014'},
     {'footnotes': [{}],
      'period': 'M02',
      'periodName': 'February',
      'value': '234.781',
      'year': '2014'},
     {'footnotes': [{}],
      'period': 'M01',
      'periodName': 'January',
      'value': '233.916',
      'year': '2014'},
     {'footnotes': [{}],
      'period': 'M12',
      'periodName': 'December',
      'value': '233.049',
      'year': '2013'},
     {'footnotes': [{}],
      'period': 'M11',
      'periodName': 'November',
      'value': '233.069',
      'year': '2013'},
     {'footnotes': [{}],
      'period': 'M10',
      'periodName': 'October',
      'value': '233.546',
      'year': '2013'},
     {'footnotes': [{}],
      'period': 'M09',
      'periodName': 'September',
      'value': '234.149',
      'year': '2013'},
     {'footnotes': [{}],
      'period': 'M08',
      'periodName': 'August',
      'value': '233.877',
      'year': '2013'},
     {'footnotes': [{}],
      'period': 'M07',
      'periodName': 'July',
      'value': '233.596',
      'year': '2013'},
     {'footnotes': [{}],
      'period': 'M06',
      'periodName': 'June',
      'value': '233.504',
      'year': '2013'},
     {'footnotes': [{}],
      'period': 'M05',
      'periodName': 'May',
      'value': '232.945',
      'year': '2013'},
     {'footnotes': [{}],
      'period': 'M04',
      'periodName': 'April',
      'value': '232.531',
      'year': '2013'},
     {'footnotes': [{}],
      'period': 'M03',
      'periodName': 'March',
      'value': '232.773',
      'year': '2013'},
     {'footnotes': [{}],
      'period': 'M02',
      'periodName': 'February',
      'value': '232.166',
      'year': '2013'},
     {'footnotes': [{}],
      'period': 'M01',
      'periodName': 'January',
      'value': '230.280',
      'year': '2013'},
     {'footnotes': [{}],
      'period': 'M12',
      'periodName': 'December',
      'value': '229.601',
      'year': '2012'},
     {'footnotes': [{}],
      'period': 'M11',
      'periodName': 'November',
      'value': '230.221',
      'year': '2012'},
     {'footnotes': [{}],
      'period': 'M10',
      'periodName': 'October',
      'value': '231.317',
      'year': '2012'},
     {'footnotes': [{}],
      'period': 'M09',
      'periodName': 'September',
      'value': '231.407',
      'year': '2012'},
     {'footnotes': [{}],
      'period': 'M08',
      'periodName': 'August',
      'value': '230.379',
      'year': '2012'},
     {'footnotes': [{}],
      'period': 'M07',
      'periodName': 'July',
      'value': '229.104',
      'year': '2012'},
     {'footnotes': [{}],
      'period': 'M06',
      'periodName': 'June',
      'value': '229.478',
      'year': '2012'},
     {'footnotes': [{}],
      'period': 'M05',
      'periodName': 'May',
      'value': '229.815',
      'year': '2012'},
     {'footnotes': [{}],
      'period': 'M04',
      'periodName': 'April',
      'value': '230.085',
      'year': '2012'},
     {'footnotes': [{}],
      'period': 'M03',
      'periodName': 'March',
      'value': '229.392',
      'year': '2012'},
     {'footnotes': [{}],
      'period': 'M02',
      'periodName': 'February',
      'value': '227.663',
      'year': '2012'},
     {'footnotes': [{}],
      'period': 'M01',
      'periodName': 'January',
      'value': '226.665',
      'year': '2012'},
     {'footnotes': [{}],
      'period': 'M12',
      'periodName': 'December',
      'value': '225.672',
      'year': '2011'},
     {'footnotes': [{}],
      'period': 'M11',
      'periodName': 'November',
      'value': '226.230',
      'year': '2011'},
     {'footnotes': [{}],
      'period': 'M10',
      'periodName': 'October',
      'value': '226.421',
      'year': '2011'},
     {'footnotes': [{}],
      'period': 'M09',
      'periodName': 'September',
      'value': '226.889',
      'year': '2011'},
     {'footnotes': [{}],
      'period': 'M08',
      'periodName': 'August',
      'value': '226.545',
      'year': '2011'},
     {'footnotes': [{}],
      'period': 'M07',
      'periodName': 'July',
      'value': '225.922',
      'year': '2011'},
     {'footnotes': [{}],
      'period': 'M06',
      'periodName': 'June',
      'value': '225.722',
      'year': '2011'},
     {'footnotes': [{}],
      'period': 'M05',
      'periodName': 'May',
      'value': '225.964',
      'year': '2011'},
     {'footnotes': [{}],
      'period': 'M04',
      'periodName': 'April',
      'value': '224.906',
      'year': '2011'},
     {'footnotes': [{}],
      'period': 'M03',
      'periodName': 'March',
      'value': '223.467',
      'year': '2011'},
     {'footnotes': [{}],
      'period': 'M02',
      'periodName': 'February',
      'value': '221.309',
      'year': '2011'},
     {'footnotes': [{}],
      'period': 'M01',
      'periodName': 'January',
      'value': '220.223',
      'year': '2011'}],
    'seriesID': 'CUUR0000SA0'},
   {'data': [{'footnotes': [{}],
      'period': 'M12',
      'periodName': 'December',
      'value': '134.207',
      'year': '2014'},
     {'footnotes': [{}],
      'period': 'M11',
      'periodName': 'November',
      'value': '135.107',
      'year': '2014'},
     {'footnotes': [{}],
      'period': 'M10',
      'periodName': 'October',
      'value': '135.891',
      'year': '2014'},
     {'footnotes': [{}],
      'period': 'M09',
      'periodName': 'September',
      'value': '136.211',
      'year': '2014'},
     {'footnotes': [{}],
      'period': 'M08',
      'periodName': 'August',
      'value': '136.127',
      'year': '2014'},
     {'footnotes': [{}],
      'period': 'M07',
      'periodName': 'July',
      'value': '136.392',
      'year': '2014'},
     {'footnotes': [{}],
      'period': 'M06',
      'periodName': 'June',
      'value': '136.433',
      'year': '2014'},
     {'footnotes': [{}],
      'period': 'M05',
      'periodName': 'May',
      'value': '136.216',
      'year': '2014'},
     {'footnotes': [{}],
      'period': 'M04',
      'periodName': 'April',
      'value': '135.771',
      'year': '2014'},
     {'footnotes': [{}],
      'period': 'M03',
      'periodName': 'March',
      'value': '135.375',
      'year': '2014'},
     {'footnotes': [{}],
      'period': 'M02',
      'periodName': 'February',
      'value': '134.542',
      'year': '2014'},
     {'footnotes': [{}],
      'period': 'M01',
      'periodName': 'January',
      'value': '134.017',
      'year': '2014'},
     {'footnotes': [{}],
      'period': 'M12',
      'periodName': 'December',
      'value': '133.509',
      'year': '2013'},
     {'footnotes': [{}],
      'period': 'M11',
      'periodName': 'November',
      'value': '133.596',
      'year': '2013'},
     {'footnotes': [{}],
      'period': 'M10',
      'periodName': 'October',
      'value': '133.876',
      'year': '2013'},
     {'footnotes': [{}],
      'period': 'M09',
      'periodName': 'September',
      'value': '134.255',
      'year': '2013'},
     {'footnotes': [{}],
      'period': 'M08',
      'periodName': 'August',
      'value': '134.098',
      'year': '2013'},
     {'footnotes': [{}],
      'period': 'M07',
      'periodName': 'July',
      'value': '133.919',
      'year': '2013'},
     {'footnotes': [{}],
      'period': 'M06',
      'periodName': 'June',
      'value': '133.900',
      'year': '2013'},
     {'footnotes': [{}],
      'period': 'M05',
      'periodName': 'May',
      'value': '133.626',
      'year': '2013'},
     {'footnotes': [{}],
      'period': 'M04',
      'periodName': 'April',
      'value': '133.421',
      'year': '2013'},
     {'footnotes': [{}],
      'period': 'M03',
      'periodName': 'March',
      'value': '133.558',
      'year': '2013'},
     {'footnotes': [{}],
      'period': 'M02',
      'periodName': 'February',
      'value': '133.204',
      'year': '2013'},
     {'footnotes': [{}],
      'period': 'M01',
      'periodName': 'January',
      'value': '132.137',
      'year': '2013'},
     {'footnotes': [{}],
      'period': 'M12',
      'periodName': 'December',
      'value': '131.770',
      'year': '2012'},
     {'footnotes': [{}],
      'period': 'M11',
      'periodName': 'November',
      'value': '132.208',
      'year': '2012'},
     {'footnotes': [{}],
      'period': 'M10',
      'periodName': 'October',
      'value': '132.892',
      'year': '2012'},
     {'footnotes': [{}],
      'period': 'M09',
      'periodName': 'September',
      'value': '132.988',
      'year': '2012'},
     {'footnotes': [{}],
      'period': 'M08',
      'periodName': 'August',
      'value': '132.430',
      'year': '2012'},
     {'footnotes': [{}],
      'period': 'M07',
      'periodName': 'July',
      'value': '131.731',
      'year': '2012'},
     {'footnotes': [{}],
      'period': 'M06',
      'periodName': 'June',
      'value': '131.956',
      'year': '2012'},
     {'footnotes': [{}],
      'period': 'M05',
      'periodName': 'May',
      'value': '132.154',
      'year': '2012'},
     {'footnotes': [{}],
      'period': 'M04',
      'periodName': 'April',
      'value': '132.284',
      'year': '2012'},
     {'footnotes': [{}],
      'period': 'M03',
      'periodName': 'March',
      'value': '131.905',
      'year': '2012'},
     {'footnotes': [{}],
      'period': 'M02',
      'periodName': 'February',
      'value': '130.953',
      'year': '2012'},
     {'footnotes': [{}],
      'period': 'M01',
      'periodName': 'January',
      'value': '130.438',
      'year': '2012'},
     {'footnotes': [{}],
      'period': 'M12',
      'periodName': 'December',
      'value': '129.844',
      'year': '2011'},
     {'footnotes': [{}],
      'period': 'M11',
      'periodName': 'November',
      'value': '130.196',
      'year': '2011'},
     {'footnotes': [{}],
      'period': 'M10',
      'periodName': 'October',
      'value': '130.373',
      'year': '2011'},
     {'footnotes': [{}],
      'period': 'M09',
      'periodName': 'September',
      'value': '130.635',
      'year': '2011'},
     {'footnotes': [{}],
      'period': 'M08',
      'periodName': 'August',
      'value': '130.351',
      'year': '2011'},
     {'footnotes': [{}],
      'period': 'M07',
      'periodName': 'July',
      'value': '129.983',
      'year': '2011'},
     {'footnotes': [{}],
      'period': 'M06',
      'periodName': 'June',
      'value': '129.846',
      'year': '2011'},
     {'footnotes': [{}],
      'period': 'M05',
      'periodName': 'May',
      'value': '129.999',
      'year': '2011'},
     {'footnotes': [{}],
      'period': 'M04',
      'periodName': 'April',
      'value': '129.483',
      'year': '2011'},
     {'footnotes': [{}],
      'period': 'M03',
      'periodName': 'March',
      'value': '128.585',
      'year': '2011'},
     {'footnotes': [{}],
      'period': 'M02',
      'periodName': 'February',
      'value': '127.363',
      'year': '2011'},
     {'footnotes': [{}],
      'period': 'M01',
      'periodName': 'January',
      'value': '126.778',
      'year': '2011'}],
    'seriesID': 'SUUR0000SA0'}]},
 'message': [],
 'responseTime': 154,
 'status': 'REQUEST_SUCCEEDED'}

In [6]:
# Create pickle/bls and open it for writing, dump bls data to outfile and then close the outfile

In [7]:
BLS_PATH = os.path.join("pickle", "bls")
outfile = open(BLS_PATH, 'wb')
pickle.dump(data, outfile)
outfile.close()

In [8]:
# Unpickle

In [9]:
infile = open('bls', 'rb')
new_data = pickle.load(infile)
infile.close()

In [10]:
# Print bls content

In [11]:
print(new_data)

{'Results': {'series': [{'seriesID': 'CUUR0000SA0', 'data': [{'periodName': 'December', 'value': '234.812', 'period': 'M12', 'year': '2014', 'footnotes': [{}]}, {'periodName': 'November', 'value': '236.151', 'period': 'M11', 'year': '2014', 'footnotes': [{}]}, {'periodName': 'October', 'value': '237.433', 'period': 'M10', 'year': '2014', 'footnotes': [{}]}, {'periodName': 'September', 'value': '238.031', 'period': 'M09', 'year': '2014', 'footnotes': [{}]}, {'periodName': 'August', 'value': '237.852', 'period': 'M08', 'year': '2014', 'footnotes': [{}]}, {'periodName': 'July', 'value': '238.250', 'period': 'M07', 'year': '2014', 'footnotes': [{}]}, {'periodName': 'June', 'value': '238.343', 'period': 'M06', 'year': '2014', 'footnotes': [{}]}, {'periodName': 'May', 'value': '237.900', 'period': 'M05', 'year': '2014', 'footnotes': [{}]}, {'periodName': 'April', 'value': '237.072', 'period': 'M04', 'year': '2014', 'footnotes': [{}]}, {'periodName': 'March', 'value': '236.293', 'period': 'M03', 'year': '2014', 'footnotes': [{}]}, {'periodName': 'February', 'value': '234.781', 'period': 'M02', 'year': '2014', 'footnotes': [{}]}, {'periodName': 'January', 'value': '233.916', 'period': 'M01', 'year': '2014', 'footnotes': [{}]}, {'periodName': 'December', 'value': '233.049', 'period': 'M12', 'year': '2013', 'footnotes': [{}]}, {'periodName': 'November', 'value': '233.069', 'period': 'M11', 'year': '2013', 'footnotes': [{}]}, {'periodName': 'October', 'value': '233.546', 'period': 'M10', 'year': '2013', 'footnotes': [{}]}, {'periodName': 'September', 'value': '234.149', 'period': 'M09', 'year': '2013', 'footnotes': [{}]}, {'periodName': 'August', 'value': '233.877', 'period': 'M08', 'year': '2013', 'footnotes': [{}]}, {'periodName': 'July', 'value': '233.596', 'period': 'M07', 'year': '2013', 'footnotes': [{}]}, {'periodName': 'June', 'value': '233.504', 'period': 'M06', 'year': '2013', 'footnotes': [{}]}, {'periodName': 'May', 'value': '232.945', 'period': 'M05', 'year': '2013', 'footnotes': [{}]}, {'periodName': 'April', 'value': '232.531', 'period': 'M04', 'year': '2013', 'footnotes': [{}]}, {'periodName': 'March', 'value': '232.773', 'period': 'M03', 'year': '2013', 'footnotes': [{}]}, {'periodName': 'February', 'value': '232.166', 'period': 'M02', 'year': '2013', 'footnotes': [{}]}, {'periodName': 'January', 'value': '230.280', 'period': 'M01', 'year': '2013', 'footnotes': [{}]}, {'periodName': 'December', 'value': '229.601', 'period': 'M12', 'year': '2012', 'footnotes': [{}]}, {'periodName': 'November', 'value': '230.221', 'period': 'M11', 'year': '2012', 'footnotes': [{}]}, {'periodName': 'October', 'value': '231.317', 'period': 'M10', 'year': '2012', 'footnotes': [{}]}, {'periodName': 'September', 'value': '231.407', 'period': 'M09', 'year': '2012', 'footnotes': [{}]}, {'periodName': 'August', 'value': '230.379', 'period': 'M08', 'year': '2012', 'footnotes': [{}]}, {'periodName': 'July', 'value': '229.104', 'period': 'M07', 'year': '2012', 'footnotes': [{}]}, {'periodName': 'June', 'value': '229.478', 'period': 'M06', 'year': '2012', 'footnotes': [{}]}, {'periodName': 'May', 'value': '229.815', 'period': 'M05', 'year': '2012', 'footnotes': [{}]}, {'periodName': 'April', 'value': '230.085', 'period': 'M04', 'year': '2012', 'footnotes': [{}]}, {'periodName': 'March', 'value': '229.392', 'period': 'M03', 'year': '2012', 'footnotes': [{}]}, {'periodName': 'February', 'value': '227.663', 'period': 'M02', 'year': '2012', 'footnotes': [{}]}, {'periodName': 'January', 'value': '226.665', 'period': 'M01', 'year': '2012', 'footnotes': [{}]}, {'periodName': 'December', 'value': '225.672', 'period': 'M12', 'year': '2011', 'footnotes': [{}]}, {'periodName': 'November', 'value': '226.230', 'period': 'M11', 'year': '2011', 'footnotes': [{}]}, {'periodName': 'October', 'value': '226.421', 'period': 'M10', 'year': '2011', 'footnotes': [{}]}, {'periodName': 'September', 'value': '226.889', 'period': 'M09', 'year': '2011', 'footnotes': [{}]}, {'periodName': 'August', 'value': '226.545', 'period': 'M08', 'year': '2011', 'footnotes': [{}]}, {'periodName': 'July', 'value': '225.922', 'period': 'M07', 'year': '2011', 'footnotes': [{}]}, {'periodName': 'June', 'value': '225.722', 'period': 'M06', 'year': '2011', 'footnotes': [{}]}, {'periodName': 'May', 'value': '225.964', 'period': 'M05', 'year': '2011', 'footnotes': [{}]}, {'periodName': 'April', 'value': '224.906', 'period': 'M04', 'year': '2011', 'footnotes': [{}]}, {'periodName': 'March', 'value': '223.467', 'period': 'M03', 'year': '2011', 'footnotes': [{}]}, {'periodName': 'February', 'value': '221.309', 'period': 'M02', 'year': '2011', 'footnotes': [{}]}, {'periodName': 'January', 'value': '220.223', 'period': 'M01', 'year': '2011', 'footnotes': [{}]}]}, {'seriesID': 'SUUR0000SA0', 'data': [{'periodName': 'December', 'value': '134.207', 'period': 'M12', 'year': '2014', 'footnotes': [{}]}, {'periodName': 'November', 'value': '135.107', 'period': 'M11', 'year': '2014', 'footnotes': [{}]}, {'periodName': 'October', 'value': '135.891', 'period': 'M10', 'year': '2014', 'footnotes': [{}]}, {'periodName': 'September', 'value': '136.211', 'period': 'M09', 'year': '2014', 'footnotes': [{}]}, {'periodName': 'August', 'value': '136.127', 'period': 'M08', 'year': '2014', 'footnotes': [{}]}, {'periodName': 'July', 'value': '136.392', 'period': 'M07', 'year': '2014', 'footnotes': [{}]}, {'periodName': 'June', 'value': '136.433', 'period': 'M06', 'year': '2014', 'footnotes': [{}]}, {'periodName': 'May', 'value': '136.216', 'period': 'M05', 'year': '2014', 'footnotes': [{}]}, {'periodName': 'April', 'value': '135.771', 'period': 'M04', 'year': '2014', 'footnotes': [{}]}, {'periodName': 'March', 'value': '135.375', 'period': 'M03', 'year': '2014', 'footnotes': [{}]}, {'periodName': 'February', 'value': '134.542', 'period': 'M02', 'year': '2014', 'footnotes': [{}]}, {'periodName': 'January', 'value': '134.017', 'period': 'M01', 'year': '2014', 'footnotes': [{}]}, {'periodName': 'December', 'value': '133.509', 'period': 'M12', 'year': '2013', 'footnotes': [{}]}, {'periodName': 'November', 'value': '133.596', 'period': 'M11', 'year': '2013', 'footnotes': [{}]}, {'periodName': 'October', 'value': '133.876', 'period': 'M10', 'year': '2013', 'footnotes': [{}]}, {'periodName': 'September', 'value': '134.255', 'period': 'M09', 'year': '2013', 'footnotes': [{}]}, {'periodName': 'August', 'value': '134.098', 'period': 'M08', 'year': '2013', 'footnotes': [{}]}, {'periodName': 'July', 'value': '133.919', 'period': 'M07', 'year': '2013', 'footnotes': [{}]}, {'periodName': 'June', 'value': '133.900', 'period': 'M06', 'year': '2013', 'footnotes': [{}]}, {'periodName': 'May', 'value': '133.626', 'period': 'M05', 'year': '2013', 'footnotes': [{}]}, {'periodName': 'April', 'value': '133.421', 'period': 'M04', 'year': '2013', 'footnotes': [{}]}, {'periodName': 'March', 'value': '133.558', 'period': 'M03', 'year': '2013', 'footnotes': [{}]}, {'periodName': 'February', 'value': '133.204', 'period': 'M02', 'year': '2013', 'footnotes': [{}]}, {'periodName': 'January', 'value': '132.137', 'period': 'M01', 'year': '2013', 'footnotes': [{}]}, {'periodName': 'December', 'value': '131.770', 'period': 'M12', 'year': '2012', 'footnotes': [{}]}, {'periodName': 'November', 'value': '132.208', 'period': 'M11', 'year': '2012', 'footnotes': [{}]}, {'periodName': 'October', 'value': '132.892', 'period': 'M10', 'year': '2012', 'footnotes': [{}]}, {'periodName': 'September', 'value': '132.988', 'period': 'M09', 'year': '2012', 'footnotes': [{}]}, {'periodName': 'August', 'value': '132.430', 'period': 'M08', 'year': '2012', 'footnotes': [{}]}, {'periodName': 'July', 'value': '131.731', 'period': 'M07', 'year': '2012', 'footnotes': [{}]}, {'periodName': 'June', 'value': '131.956', 'period': 'M06', 'year': '2012', 'footnotes': [{}]}, {'periodName': 'May', 'value': '132.154', 'period': 'M05', 'year': '2012', 'footnotes': [{}]}, {'periodName': 'April', 'value': '132.284', 'period': 'M04', 'year': '2012', 'footnotes': [{}]}, {'periodName': 'March', 'value': '131.905', 'period': 'M03', 'year': '2012', 'footnotes': [{}]}, {'periodName': 'February', 'value': '130.953', 'period': 'M02', 'year': '2012', 'footnotes': [{}]}, {'periodName': 'January', 'value': '130.438', 'period': 'M01', 'year': '2012', 'footnotes': [{}]}, {'periodName': 'December', 'value': '129.844', 'period': 'M12', 'year': '2011', 'footnotes': [{}]}, {'periodName': 'November', 'value': '130.196', 'period': 'M11', 'year': '2011', 'footnotes': [{}]}, {'periodName': 'October', 'value': '130.373', 'period': 'M10', 'year': '2011', 'footnotes': [{}]}, {'periodName': 'September', 'value': '130.635', 'period': 'M09', 'year': '2011', 'footnotes': [{}]}, {'periodName': 'August', 'value': '130.351', 'period': 'M08', 'year': '2011', 'footnotes': [{}]}, {'periodName': 'July', 'value': '129.983', 'period': 'M07', 'year': '2011', 'footnotes': [{}]}, {'periodName': 'June', 'value': '129.846', 'period': 'M06', 'year': '2011', 'footnotes': [{}]}, {'periodName': 'May', 'value': '129.999', 'period': 'M05', 'year': '2011', 'footnotes': [{}]}, {'periodName': 'April', 'value': '129.483', 'period': 'M04', 'year': '2011', 'footnotes': [{}]}, {'periodName': 'March', 'value': '128.585', 'period': 'M03', 'year': '2011', 'footnotes': [{}]}, {'periodName': 'February', 'value': '127.363', 'period': 'M02', 'year': '2011', 'footnotes': [{}]}, {'periodName': 'January', 'value': '126.778', 'period': 'M01', 'year': '2011', 'footnotes': [{}]}]}]}, 'message': [], 'status': 'REQUEST_SUCCEEDED', 'responseTime': 164}

In [16]:
print(type(new_data))

<class 'dict'>

In [17]:
from pandas.io.json import json_normalize
import pandas as pd

In [18]:
df = pd.DataFrame.from_dict(json_normalize(data['Results']['series']), orient='columns')
df

                                                data     seriesID
0  [{'periodName': 'December', 'value': '234.812'...  CUUR0000SA0
1  [{'periodName': 'December', 'value': '134.207'...  SUUR0000SA0

In [19]:
data['seriesID']

KeyError: 'seriesID'